# -*- coding: utf-8 -*-
"""converter_json_casaccia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kj5JmTZnBE8EIl6coNDC2FC2DbYJkQtI
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import json
from datetime import datetime


def excel_to_json(excel_file):
    # Leggi il file Excel saltando le prime due righe di intestazione
    df = pd.read_excel(excel_file, header=None, skiprows=[0,1])

    # Dizionario per il risultato finale
    result = {}

    # Itera su ogni riga del DataFrame
    for index, row in df.iterrows():
        # Crea il timestamp combinando data e ora
        date = row.iloc[0].strftime('%d/%m/%Y') if isinstance(row.iloc[0], datetime) else row.iloc[0]
        time = row.iloc[1] if isinstance(row.iloc[1], str) else row.iloc[1].strftime('%H:%M:%S')
        timestamp = f"{date} - {time}"

        # Inizializza il dizionario per questo timestamp
        entry = {
            "GHI": {
                "Real": row.iloc[2],  # Colonna C
                "MM5": row.iloc[3],  # Colonna D
                "Prediction": row.iloc[4]  # Colonna E
            },
            "Temperature": {
                "Real": row.iloc[5],  # Colonna F
                "MM5": row.iloc[6],  # Colonna G
                "Prediction": row.iloc[7]  # Colonna H
            },
            "Wind speed 10m": {
                "Real": row.iloc[8],  # Colonna I
                "MM5": row.iloc[9],  # Colonna J
                "Prediction": row.iloc[10]  # Colonna K
            },
            "Wind direction 10m": {
                "Real": row.iloc[11],  # Colonna L
                "MM5": row.iloc[12],  # Colonna M
                "Prediction": row.iloc[13]  # Colonna N
            }
        }

        result[timestamp] = entry

    return result


def save_json(data, output_file):
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def main():
    # Percorso del file Excel
    excel_file = '/content/drive/MyDrive/Dati variabili metereologiche Casaccia.xlsx'  # Modifica con il nome corretto del tuo file

    # Percorso del file JSON di output
    output_file = '/content/drive/MyDrive/json_Casaccia.json'

    # Converti Excel in JSON
    data = excel_to_json(excel_file)

    # Salva il risultato in un file JSON
    save_json(data, output_file)

    print(f"Conversione completata. Il file JSON è stato salvato come '{output_file}'")


if __name__ == "__main__":
    main()